// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto.Infrastructure.Data;

#nullable disable

namespace Proyecto.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20251129164352_AgregarEspecialidadUsuario")]
    partial class AgregarEspecialidadUsuario
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseConocimientoEtiqueta", b =>
                {
                    b.Property<int>("ArticulosConocimientoId")
                        .HasColumnType("int");

                    b.Property<int>("EtiquetasId")
                        .HasColumnType("int");

                    b.HasKey("ArticulosConocimientoId", "EtiquetasId");

                    b.HasIndex("EtiquetasId");

                    b.ToTable("BaseConocimientoEtiqueta", (string)null);
                });

            modelBuilder.Entity("EtiquetaIncidente", b =>
                {
                    b.Property<int>("EtiquetasId")
                        .HasColumnType("int");

                    b.Property<int>("IncidentesId")
                        .HasColumnType("int");

                    b.HasKey("EtiquetasId", "IncidentesId");

                    b.HasIndex("IncidentesId");

                    b.ToTable("IncidenteEtiqueta", (string)null);
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.BaseConocimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Solucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("VecesConsultada")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorId");

                    b.ToTable("BaseConocimiento");
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.Etiqueta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Etiquetas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = 1,
                            Descripcion = "Problemas de hardware",
                            Nombre = "Hardware"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = 2,
                            Descripcion = "Problemas de software",
                            Nombre = "Software"
                        },
                        new
                        {
                            Id = 3,
                            Categoria = 3,
                            Descripcion = "Problemas de red",
                            Nombre = "Red"
                        },
                        new
                        {
                            Id = 4,
                            Categoria = 4,
                            Descripcion = "Problemas con impresoras",
                            Nombre = "Impresora"
                        },
                        new
                        {
                            Id = 5,
                            Categoria = 7,
                            Descripcion = "Problemas con correo electrónico",
                            Nombre = "Email"
                        },
                        new
                        {
                            Id = 6,
                            Categoria = 5,
                            Descripcion = "Problemas con Windows",
                            Nombre = "Windows"
                        },
                        new
                        {
                            Id = 7,
                            Categoria = 6,
                            Descripcion = "Problemas con Office",
                            Nombre = "Office"
                        });
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.Incidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IncidentePadreId")
                        .HasColumnType("int");

                    b.Property<string>("MensajeEscalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("Resolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("UsuarioAsignadoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioReportaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidentePadreId");

                    b.HasIndex("UsuarioAsignadoId");

                    b.HasIndex("UsuarioReportaId");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@universidad.edu",
                            Especialidad = "Administración General",
                            FechaCreacion = new DateTime(2025, 11, 29, 11, 43, 51, 692, DateTimeKind.Local).AddTicks(9434),
                            Nivel = 4,
                            Nombre = "Admin Principal",
                            PasswordHash = "admin123"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "tecnico3@universidad.edu",
                            Especialidad = "Redes y Servidores",
                            FechaCreacion = new DateTime(2025, 11, 29, 11, 43, 51, 692, DateTimeKind.Local).AddTicks(9439),
                            Nivel = 3,
                            Nombre = "Técnico Avanzado",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Email = "tecnico2@universidad.edu",
                            Especialidad = "Software y Aplicaciones",
                            FechaCreacion = new DateTime(2025, 11, 29, 11, 43, 51, 692, DateTimeKind.Local).AddTicks(9442),
                            Nivel = 2,
                            Nombre = "Técnico Básico",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Email = "tecnico1@universidad.edu",
                            Especialidad = "Soporte Básico",
                            FechaCreacion = new DateTime(2025, 11, 29, 11, 43, 51, 692, DateTimeKind.Local).AddTicks(9445),
                            Nivel = 1,
                            Nombre = "Técnico Nivel 1",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Email = "estudiante1@universidad.edu",
                            FechaCreacion = new DateTime(2025, 11, 29, 11, 43, 51, 692, DateTimeKind.Local).AddTicks(9448),
                            Nivel = 0,
                            Nombre = "Juan Pérez",
                            PasswordHash = "estudiante123"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Email = "estudiante2@universidad.edu",
                            FechaCreacion = new DateTime(2025, 11, 29, 11, 43, 51, 692, DateTimeKind.Local).AddTicks(9451),
                            Nivel = 0,
                            Nombre = "María González",
                            PasswordHash = "estudiante123"
                        });
                });

            modelBuilder.Entity("BaseConocimientoEtiqueta", b =>
                {
                    b.HasOne("Proyecto.Domain.Entities.BaseConocimiento", null)
                        .WithMany()
                        .HasForeignKey("ArticulosConocimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto.Domain.Entities.Etiqueta", null)
                        .WithMany()
                        .HasForeignKey("EtiquetasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EtiquetaIncidente", b =>
                {
                    b.HasOne("Proyecto.Domain.Entities.Etiqueta", null)
                        .WithMany()
                        .HasForeignKey("EtiquetasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto.Domain.Entities.Incidente", null)
                        .WithMany()
                        .HasForeignKey("IncidentesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.BaseConocimiento", b =>
                {
                    b.HasOne("Proyecto.Domain.Entities.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.Incidente", b =>
                {
                    b.HasOne("Proyecto.Domain.Entities.Incidente", "IncidentePadre")
                        .WithMany("IncidentesEscalados")
                        .HasForeignKey("IncidentePadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto.Domain.Entities.Usuario", "UsuarioAsignado")
                        .WithMany("IncidentesAsignados")
                        .HasForeignKey("UsuarioAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto.Domain.Entities.Usuario", "UsuarioReporta")
                        .WithMany("IncidentesReportados")
                        .HasForeignKey("UsuarioReportaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IncidentePadre");

                    b.Navigation("UsuarioAsignado");

                    b.Navigation("UsuarioReporta");
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("Proyecto.Domain.Entities.Incidente", "Incidente")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Proyecto.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incidente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.Incidente", b =>
                {
                    b.Navigation("IncidentesEscalados");

                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("IncidentesAsignados");

                    b.Navigation("IncidentesReportados");

                    b.Navigation("Notificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
