// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Proyecto.Infrastructure.Data;

#nullable disable

namespace Proyecto.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    partial class ApplicationDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.0")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("BaseConocimientoEtiqueta", b =>
                {
                    b.Property<int>("ArticulosConocimientoId")
                        .HasColumnType("int");

                    b.Property<int>("EtiquetasId")
                        .HasColumnType("int");

                    b.HasKey("ArticulosConocimientoId", "EtiquetasId");

                    b.HasIndex("EtiquetasId");

                    b.ToTable("BaseConocimientoEtiqueta", (string)null);
                });

            modelBuilder.Entity("EtiquetaIncidente", b =>
                {
                    b.Property<int>("EtiquetasId")
                        .HasColumnType("int");

                    b.Property<int>("IncidentesId")
                        .HasColumnType("int");

                    b.HasKey("EtiquetasId", "IncidentesId");

                    b.HasIndex("IncidentesId");

                    b.ToTable("IncidenteEtiqueta", (string)null);
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.BaseConocimiento", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("CreadoPorId")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("FechaActualizacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<string>("Solucion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int>("VecesConsultada")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("CreadoPorId");

                    b.ToTable("BaseConocimiento");
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.Etiqueta", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<int>("Categoria")
                        .HasColumnType("int");

                    b.Property<string>("Descripcion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.HasKey("Id");

                    b.HasIndex("Nombre")
                        .IsUnique();

                    b.ToTable("Etiquetas");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Categoria = 1,
                            Descripcion = "Problemas de hardware",
                            Nombre = "Hardware"
                        },
                        new
                        {
                            Id = 2,
                            Categoria = 2,
                            Descripcion = "Problemas de software",
                            Nombre = "Software"
                        },
                        new
                        {
                            Id = 3,
                            Categoria = 3,
                            Descripcion = "Problemas de red",
                            Nombre = "Red"
                        },
                        new
                        {
                            Id = 4,
                            Categoria = 4,
                            Descripcion = "Problemas con impresoras",
                            Nombre = "Impresora"
                        },
                        new
                        {
                            Id = 5,
                            Categoria = 7,
                            Descripcion = "Problemas con correo electrónico",
                            Nombre = "Email"
                        },
                        new
                        {
                            Id = 6,
                            Categoria = 5,
                            Descripcion = "Problemas con Windows",
                            Nombre = "Windows"
                        },
                        new
                        {
                            Id = 7,
                            Categoria = 6,
                            Descripcion = "Problemas con Office",
                            Nombre = "Office"
                        });
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.Incidente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("Descripcion")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Estado")
                        .HasColumnType("int");

                    b.Property<DateTime?>("FechaAsignacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaResolucion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IncidentePadreId")
                        .HasColumnType("int");

                    b.Property<string>("MensajeEscalacion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("MotivoDescarte")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Prioridad")
                        .HasColumnType("int");

                    b.Property<string>("Resolucion")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Titulo")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("nvarchar(300)");

                    b.Property<int?>("UsuarioAsignadoId")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioReportaId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidentePadreId");

                    b.HasIndex("UsuarioAsignadoId");

                    b.HasIndex("UsuarioReportaId");

                    b.ToTable("Incidentes");
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.Notificacion", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int?>("IncidenteId")
                        .HasColumnType("int");

                    b.Property<bool>("Leida")
                        .HasColumnType("bit");

                    b.Property<string>("Mensaje")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int>("Tipo")
                        .HasColumnType("int");

                    b.Property<int>("UsuarioId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("IncidenteId");

                    b.HasIndex("UsuarioId");

                    b.ToTable("Notificaciones");
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.Usuario", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<bool>("Activo")
                        .HasColumnType("bit");

                    b.Property<string>("Email")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Especialidad")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateTime>("FechaCreacion")
                        .HasColumnType("datetime2");

                    b.Property<int>("Nivel")
                        .HasColumnType("int");

                    b.Property<string>("Nombre")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("PasswordHash")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("Email")
                        .IsUnique();

                    b.ToTable("Usuarios");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Activo = true,
                            Email = "admin@universidad.edu",
                            Especialidad = "Administración General",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9378),
                            Nivel = 5,
                            Nombre = "Admin Principal",
                            PasswordHash = "admin123"
                        },
                        new
                        {
                            Id = 2,
                            Activo = true,
                            Email = "carlos.mendoza@universidad.edu",
                            Especialidad = "Infraestructura Cloud",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9381),
                            Nivel = 4,
                            Nombre = "Carlos Mendoza",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 3,
                            Activo = true,
                            Email = "ana.ruiz@universidad.edu",
                            Especialidad = "Seguridad Informática",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9384),
                            Nivel = 4,
                            Nombre = "Ana Patricia Ruiz",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 4,
                            Activo = true,
                            Email = "roberto.sanchez@universidad.edu",
                            Especialidad = "Arquitectura de Sistemas",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9386),
                            Nivel = 4,
                            Nombre = "Roberto Sánchez",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 5,
                            Activo = true,
                            Email = "laura.fernandez@universidad.edu",
                            Especialidad = "DevOps y Automatización",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9388),
                            Nivel = 4,
                            Nombre = "Laura Fernández",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 6,
                            Activo = true,
                            Email = "miguel.torres@universidad.edu",
                            Especialidad = "Ciberseguridad",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9400),
                            Nivel = 4,
                            Nombre = "Miguel Ángel Torres",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 7,
                            Activo = true,
                            Email = "patricia.morales@universidad.edu",
                            Especialidad = "Administración de Redes",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9402),
                            Nivel = 3,
                            Nombre = "Patricia Morales",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 8,
                            Activo = true,
                            Email = "jorge.ramirez@universidad.edu",
                            Especialidad = "Servidores y Virtualización",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9404),
                            Nivel = 3,
                            Nombre = "Jorge Luis Ramírez",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 9,
                            Activo = true,
                            Email = "sofia.castro@universidad.edu",
                            Especialidad = "Redes Inalámbricas",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9405),
                            Nivel = 3,
                            Nombre = "Sofía Castro",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 10,
                            Activo = true,
                            Email = "diego.herrera@universidad.edu",
                            Especialidad = "Bases de Datos",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9407),
                            Nivel = 3,
                            Nombre = "Diego Herrera",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 11,
                            Activo = true,
                            Email = "valentina.lopez@universidad.edu",
                            Especialidad = "Almacenamiento y Backup",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9410),
                            Nivel = 3,
                            Nombre = "Valentina López",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 12,
                            Activo = true,
                            Email = "andres.jimenez@universidad.edu",
                            Especialidad = "Desarrollo Web",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9412),
                            Nivel = 2,
                            Nombre = "Andrés Jiménez",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 13,
                            Activo = true,
                            Email = "camila.vargas@universidad.edu",
                            Especialidad = "Aplicaciones Empresariales",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9414),
                            Nivel = 2,
                            Nombre = "Camila Vargas",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 14,
                            Activo = true,
                            Email = "felipe.ortiz@universidad.edu",
                            Especialidad = "Integración de Sistemas",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9416),
                            Nivel = 2,
                            Nombre = "Felipe Ortiz",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 15,
                            Activo = true,
                            Email = "daniela.rojas@universidad.edu",
                            Especialidad = "Plataformas Educativas",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9418),
                            Nivel = 2,
                            Nombre = "Daniela Rojas",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 16,
                            Activo = true,
                            Email = "sebastian.pena@universidad.edu",
                            Especialidad = "Software de Gestión",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9419),
                            Nivel = 2,
                            Nombre = "Sebastián Peña",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 17,
                            Activo = true,
                            Email = "gabriela.munoz@universidad.edu",
                            Especialidad = "Soporte Técnico General",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9421),
                            Nivel = 1,
                            Nombre = "Gabriela Muñoz",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 18,
                            Activo = true,
                            Email = "alejandro.cruz@universidad.edu",
                            Especialidad = "Atención al Usuario",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9423),
                            Nivel = 1,
                            Nombre = "Alejandro Cruz",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 19,
                            Activo = true,
                            Email = "isabella.romero@universidad.edu",
                            Especialidad = "Hardware y Mantenimiento",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9453),
                            Nivel = 1,
                            Nombre = "Isabella Romero",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 20,
                            Activo = true,
                            Email = "mateo.silva@universidad.edu",
                            Especialidad = "Soporte de Office",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9455),
                            Nivel = 1,
                            Nombre = "Mateo Silva",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 21,
                            Activo = true,
                            Email = "lucia.martinez@universidad.edu",
                            Especialidad = "Conectividad y Accesos",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9457),
                            Nivel = 1,
                            Nombre = "Lucía Martínez",
                            PasswordHash = "tecnico123"
                        },
                        new
                        {
                            Id = 22,
                            Activo = true,
                            Email = "juan.perez@universidad.edu",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9459),
                            Nivel = 0,
                            Nombre = "Juan Pablo Pérez",
                            PasswordHash = "estudiante123"
                        },
                        new
                        {
                            Id = 23,
                            Activo = true,
                            Email = "maria.gonzalez@universidad.edu",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9460),
                            Nivel = 0,
                            Nombre = "María José González",
                            PasswordHash = "estudiante123"
                        },
                        new
                        {
                            Id = 24,
                            Activo = true,
                            Email = "david.rodriguez@universidad.edu",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9462),
                            Nivel = 0,
                            Nombre = "David Rodríguez",
                            PasswordHash = "estudiante123"
                        },
                        new
                        {
                            Id = 25,
                            Activo = true,
                            Email = "carolina.diaz@universidad.edu",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9464),
                            Nivel = 0,
                            Nombre = "Carolina Díaz",
                            PasswordHash = "estudiante123"
                        },
                        new
                        {
                            Id = 26,
                            Activo = true,
                            Email = "nicolas.gomez@universidad.edu",
                            FechaCreacion = new DateTime(2025, 11, 29, 16, 52, 24, 718, DateTimeKind.Local).AddTicks(9466),
                            Nivel = 0,
                            Nombre = "Nicolás Gómez",
                            PasswordHash = "estudiante123"
                        });
                });

            modelBuilder.Entity("BaseConocimientoEtiqueta", b =>
                {
                    b.HasOne("Proyecto.Domain.Entities.BaseConocimiento", null)
                        .WithMany()
                        .HasForeignKey("ArticulosConocimientoId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto.Domain.Entities.Etiqueta", null)
                        .WithMany()
                        .HasForeignKey("EtiquetasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EtiquetaIncidente", b =>
                {
                    b.HasOne("Proyecto.Domain.Entities.Etiqueta", null)
                        .WithMany()
                        .HasForeignKey("EtiquetasId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Proyecto.Domain.Entities.Incidente", null)
                        .WithMany()
                        .HasForeignKey("IncidentesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.BaseConocimiento", b =>
                {
                    b.HasOne("Proyecto.Domain.Entities.Usuario", "CreadoPor")
                        .WithMany()
                        .HasForeignKey("CreadoPorId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("CreadoPor");
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.Incidente", b =>
                {
                    b.HasOne("Proyecto.Domain.Entities.Incidente", "IncidentePadre")
                        .WithMany("IncidentesEscalados")
                        .HasForeignKey("IncidentePadreId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto.Domain.Entities.Usuario", "UsuarioAsignado")
                        .WithMany("IncidentesAsignados")
                        .HasForeignKey("UsuarioAsignadoId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Proyecto.Domain.Entities.Usuario", "UsuarioReporta")
                        .WithMany("IncidentesReportados")
                        .HasForeignKey("UsuarioReportaId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("IncidentePadre");

                    b.Navigation("UsuarioAsignado");

                    b.Navigation("UsuarioReporta");
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.Notificacion", b =>
                {
                    b.HasOne("Proyecto.Domain.Entities.Incidente", "Incidente")
                        .WithMany("Notificaciones")
                        .HasForeignKey("IncidenteId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Proyecto.Domain.Entities.Usuario", "Usuario")
                        .WithMany("Notificaciones")
                        .HasForeignKey("UsuarioId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Incidente");

                    b.Navigation("Usuario");
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.Incidente", b =>
                {
                    b.Navigation("IncidentesEscalados");

                    b.Navigation("Notificaciones");
                });

            modelBuilder.Entity("Proyecto.Domain.Entities.Usuario", b =>
                {
                    b.Navigation("IncidentesAsignados");

                    b.Navigation("IncidentesReportados");

                    b.Navigation("Notificaciones");
                });
#pragma warning restore 612, 618
        }
    }
}
